#!/bin/bash

gcloud compute instances delete development
gcloud compute instances create development --zone us-central1-b \
  --machine-type n1-standard-1 \
  --metadata-from-file user-data=development.yml \
  --disk name=development-docker,device-name=development-docker \
  --subnet private \
  --image https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-alpha-1081-2-0-v20160627
