#!/bin/bash

AUTH_URL="http://flowercluster:8200/v1/auth/approle/login"

ROLE_ID=156ce5e6-9c7c-bbda-960c-25ca4ccd3f95
SECRET_ID=$1

printf '{"role_id":"%s","secret_id":"%s"}' $ROLE_ID $SECRET_ID | curl -v -X POST -d @- $AUTH_URL
