#!/bin/bash

UNWRAP_URL="http://flowercluster:8200/v1/sys/wrapping/unwrap"
SECRET_TOKEN=$1

RESPONSE=$(curl -X POST -H "X-Vault-Token: ${SECRET_TOKEN}" $UNWRAP_URL 2>/dev/null)

TOKEN=$(jq -r '.data.secret_id' <<< "$RESPONSE")

if [[ $TOKEN == 'null' ]]; then
  echo "failed to fetch SecretID:"
  jq '.' <<< "$RESOPNSE"

  exit 1
else
  echo $TOKEN
fi
