#!/bin/bash

UNWRAP_URL="http://flowercluster:8200/v1/sys/wrapping/unwrap"
SECRET_TOKEN=$(cat /var/local/SECRET_TOKEN)

curl -X POST -H "X-Vault-Token: ${SECRET_TOKEN}" $UNWRAP_URL | jq '.data.secret_id'
