#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
  echo "Re-running with sudo."
  exec sudo $0
fi

cd /var/local/ansible && sudo -u ansible git pull
ansible-playbook -i hosts site.yml --vault-password-file=/usr/sbin/vault_pass "$@"
