#!/bin/bash

VAULT_URL="http://flowercluster:8200/v1/secret/ansible/ansible_vault"
RENEW_URL="http://flowercluster:8200/v1/auth/token/renew-self"

TOKEN=$(cat /root/vault_token)

# renew token
curl -H "X-Vault-Token: ${TOKEN}" -X POST $RENEW_URL >/dev/null 2>&1

# get secret
curl -H "X-Vault-Token: ${TOKEN}" $VAULT_URL 2>/dev/null | jq -r '.data.pass'
