#!/bin/bash

instance_commands=( delete_instance recreate_instance launch_instance )

if [[ $# -eq 0 ]]; then
  fab -R flowercluster -l
elif [[ ${instance_commands[@]} =~ $1 ]]; then
  fab "$@"
else
  fab -R flowercluster "$@"
fi
