version: '2'

services:
  vault:
    build: .
    container_name: vault1
    volumes:
      - vault-backend:/vault/file
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: "server"

volumes:
  vault-backend:
    driver: local
