#!/bin/bash

# update git repository
(cd /opt/flowercluster && sudo git pull)

# run flowercluster/init
docker run --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /usr/bin/docker:/usr/bin/docker \
  -v /opt/flowercluster:/var/local/flowercluster \
  flowercluster/init "$@"
