#!/bin/bash

gcloud compute instances delete proxy
gcloud compute instances create proxy --zone us-central1-b \
  --machine-type n1-standard-1 \
  --metadata-from-file user-data=proxy.yml \
  --subnet public \
  --address proxy \
  --image https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-alpha-1081-2-0-v20160627
